CRAWLER_DB_USERNAME = ""
CRAWLER_DB_PASSWORD = ""
CRAWLER_DB_HOSTNAME = ""
CRAWLER_DB_PORT = ""
CRAWLER_DB_DATABASE = ""


VIRAL_DB_USERNAME = ""
VIRAL_DB_PASSWORD = ""
VIRAL_DB_HOSTNAME = ""
VIRAL_DB_PORT = ""
VIRAL_DB_DATABASE = ""
